### ISSUE TITLE
usage of identical identifier 'Clustering' for different concepts

### ISSUE THREAD

**Issue by neradis** [AKSW/mexproject#20]
mex-algo:Clustering is both used as identifier for a mex-algo:LearningProblem and a mex-algo:AlgorithmClass. This makes mex-algo:Clustering unsatisfiable, as LearningProblems
and AlgorithmClasses are declared disjoint.

We have to introduce a different identifier for either of those. My suggestion:

mex-algo:ClusteringProblem a mex-algo:LearningProblem.

mex-algo:Clustering a mex-algo:AlgorithmClass.

**Comment by dnes85** [comment]
Yes.
