### ISSUE TITLE
links

### ISSUE THREAD

**Issue by dnes85** [AKSW/mexproject#27]
update all contributors and creator's link for google plus (for instance) on the 3 mex layers.

http://lov.okfn.org/dataset/lov/vocabs/mexcore
http://lov.okfn.org/dataset/lov/vocabs/mexalgo
http://lov.okfn.org/dataset/lov/vocabs/mexperf

**Comment by mommi84** [comment]
To follow the standards, all class and instance IDs should start with a capital letter, whilst all property IDs should start with a lowercase letter.

Also, `mex-core:esteves` should be `http://aksw.org/DiegoEsteves`.
