### ISSUE TITLE
Doesn't MEX really support mls:Task?

### ISSUE THREAD

**Issue by mommi84** [AKSW/mexproject#44]
My guess is the following.

As an `:ExperimentConfiguration` may have many `:Execution`s and an `:Experiment` may have many `:ExperimentConfiguration`s, the experiment configuration could be aligned to a `mls:Task`. The ML-Schema guys agree, do you?

Also, our `:Experiment` definitely looks like OpenML's `Study`.

See [mls:Task](https://github.com/ML-Schema/core/wiki/Vocabulary#task).

**Comment by DiegoMoussallem** [comment]
I don't agree. because `mls:Task`  definition relies on in data mining(DM) field and MEX does not support DM. However, if MEX supports DM process could be `mls:run` but ML-Schema guys aligned 'run' to `mex-core: execution`. Maybe a next version of MEX covering DM.

**Comment by DiegoMoussallem** [comment]
@mommi84, Would intention be rather to align a DM task with a class that groups executions?

**Comment by mommi84** [comment]
From the definition of `mls:Task`:

> A formal description of a process that needs to be completed (e.g. based on inputs and outputs). A Task is any piece of work that needs to be addressed in the data mining process.

Here and in most definitions, _data mining_ and _machine learning_ are not considered two different fields, but rather intersected with each another. After all, the type of machine learning we describe in MEX relies on the same paradigm (input data, model, prediction).

With respect to `:Execution`, as you said, `mls:Run` is the ML-Schema counterpart. Aligning things this way I cannot see any semantic inconsistency.

**Comment by dnes85** [comment]
1 - `mexcore:ExperimentConfiguration` ~= `mls:Task`
2 - `mexcore:Experiment` ~= `mls:Study`
